name        : dcfldd
version     : 1.3.4
release     : 5
source      :
    - https://netix.dl.sourceforge.net/project/dcfldd/dcfldd/dcfldd-1.3.4/dcfldd-1.3.4.tar.gz : b7568df69c7e560054e05413f280c943757025432d8dc89d2769584867a8ca06
homepage    : http://dcfldd.sourceforge.net
license     : GPL-2.0
component   : system.utils
summary     : dcfldd - enhanced version of dd or forensics and security
description : |
    dd copies a file with a changeable I/O block size, while optionally performing conversions on it
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
