name       : dcfldd
version    : 1.3.4.1
release    : 7
source     :
    - https://sourceforge.net/projects/dcfldd/files/dcfldd/1.3.4-1/dcfldd-1.3.4-1.tar.gz/download : f5143a184da56fd5ac729d6d8cbcf9f5da8e1cf4604aa9fb97c59553b7e6d5f8
homepage   : http://dcfldd.sourceforge.net
license    : GPL-2.0
component  : system.utils
summary    : dcfldd - enhanced version of dd or forensics and security
description: |
    dd copies a file with a changeable I/O block size, while optionally performing conversions on it
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
